FROM node:18-alpine

RUN apk update && apk add g++ make python3 curl

WORKDIR /app

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG IMAGE
ARG APP_NAME
ARG APP_PORT
ARG APP_ENV
ARG APP_CORS_ORIGIN
ARG APP_CORS_ALLOWED_HEADERS
ARG APP_CORS_ALLOWED_METHODS
ARG BASE_URL
ARG DEBUG
ARG SWAGGER_USER
ARG SWAGGER_PASSWORD
ARG DB_HOST
ARG DB_DATABASE
ARG DB_USER
ARG DB_PASSWORD
ARG DB_PORT
ARG DB_POOL_SIZE
ARG DB_TYPE
ARG JWT_SECRET_KEY
ARG JWT_EXPIRES_IN
ARG JWT_REFRESH_TOKEN_EXPIRES_IN
ARG AWS_BUCKET_NAME
ARG MAIL_HOST
ARG MAIL_PORT
ARG MAIL_USERNAME
ARG MAIL_PASSWORD
ARG MAIL_SENDER
ARG MAIL_SECURE
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_CALLBACK_URL
ARG URL_FRONTEND_REDIRECT
ARG URL_KSTORE_API_REPORT
ARG N8N_WEBHOOK_URL
ARG MP_WEBHOOK_URL
ARG MP_SUCCESS_URL
ARG MP_FAILURE_URL
ARG MP_PENDING_URL

ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
    AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
    AWS_REGION=${AWS_REGION} \
    IMAGE=${IMAGE} \
    APP_NAME=${APP_NAME} \
    APP_PORT=${APP_PORT} \
    APP_ENV=${APP_ENV} \
    APP_CORS_ORIGIN=${APP_CORS_ORIGIN} \
    APP_CORS_ALLOWED_HEADERS=${APP_CORS_ALLOWED_HEADERS} \
    APP_CORS_ALLOWED_METHODS=${APP_CORS_ALLOWED_METHODS} \
    BASE_URL=${BASE_URL} \
    DEBUG=${DEBUG} \
    SWAGGER_USER=${SWAGGER_USER} \
    SWAGGER_PASSWORD=${SWAGGER_PASSWORD} \
    DB_HOST=${DB_HOST} \
    DB_DATABASE=${DB_DATABASE} \
    DB_USER=${DB_USER} \
    DB_PASSWORD=${DB_PASSWORD} \
    DB_PORT=${DB_PORT} \
    DB_POOL_SIZE=${DB_POOL_SIZE} \
    DB_TYPE=${DB_TYPE} \
    JWT_SECRET_KEY=${JWT_SECRET_KEY} \
    JWT_EXPIRES_IN=${JWT_EXPIRES_IN} \
    JWT_REFRESH_TOKEN_EXPIRES_IN=${JWT_REFRESH_TOKEN_EXPIRES_IN} \
    AWS_BUCKET_NAME=${AWS_BUCKET_NAME} \
    MAIL_HOST=${MAIL_HOST} \
    MAIL_PORT=${MAIL_PORT} \
    MAIL_USERNAME=${MAIL_USERNAME} \
    MAIL_PASSWORD=${MAIL_PASSWORD} \
    MAIL_SENDER=${MAIL_SENDER} \
    MAIL_SECURE=${MAIL_SECURE} \
    GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} \
    GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} \
    GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL} \
    URL_FRONTEND_REDIRECT=${URL_FRONTEND_REDIRECT} \
    URL_KSTORE_API_REPORT=${URL_KSTORE_API_REPORT} \
    N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL} \
    MP_WEBHOOK_URL=${MP_WEBHOOK_URL} \
    MP_SUCCESS_URL=${MP_SUCCESS_URL} \
    MP_FAILURE_URL=${MP_FAILURE_URL} \
    MP_PENDING_URL=${MP_PENDING_URL}

RUN npm install -g pm2

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["pm2-runtime", "dist/src/main.js"]